openapi: 3.0.3
info:
  title: E-Learning
  version: 1.0.0
servers:
  - url: https://apielearning-dev.bytequest.solutions/api/v1
tags:
  - name: Signup and Login
    description: Authentication Management
  - name: Google Authentication
    description: Google Authentication Management
  - name: Password
    description: Password Reset Management
  - name: Users
    description: User Management
paths:
  /auth/signup:
    post:
      tags:
        - Signup and Login
      operationId: Signup
      requestBody:
        content:
          application/json:
            schema:
              required:
                - fullName
                - email
                - password
              type: object
              properties:
                fullName:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: John.Doe@gmail.com
                password:
                  type: string
                  example: $1234abcd
      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/login:
    post:
      tags:
        - Signup and Login
      operationId: Login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
                password:
                  type: string
                  example: $1234abcd
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Login"
                  message:
                    type: string

  /auth/sso/google:
    get:
      tags:
        - Google Authentication
      operationId: Google Redirect URL
      description: Redirect to the Google Login Page
      responses:
        '200':
          description: Successful Operation
    post:
      tags:
        - Google Authentication
      operationId: Google Signup or Login
      description: Google Signup or Login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - code
              type: object
              properties:
                code:
                  type: string
                  example: 4/0AeaYSHCoSLQlzCvmwNfx_purqgyrLWJ2l2JvhmpRW9-amog1Suymw6HL64lKDfOYadviPg
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Login"
                  message:
                    type: string

  /auth/forget-password:
    post:
      tags:
        - Password
      operationId: Forget Password
      description: Send a Password Reset Link to Provided Email
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/reset-password:
    post:
      tags:
        - Password
      operationId: Reset Password
      description: Changes the Password of the User Who Requested to Reset the Password
      requestBody:
        content:
          application/json:
            schema:
              required:
                - token
                - password
              type: object
              properties:
                token:
                  type: string
                  example: 1I69UCa0BxqtIYVx23Lc
                password:
                  type: string
                  example: $1234abcd
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/me:
    get:
      tags:
        - Users
      operationId: User Profile
      description: User's All Information
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Profile"

  /users/:userid/roles:
    patch:
      tags:
        - Users
      operationId: Update User Role
      description: Update User's Role by Administrator
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              required:
                - role
              type: object
              properties:
                role:
                  type: string
                  example: student
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/update-profile:
    patch:
      tags:
        - Users
      operationId: Update Profile
      description: Update The LoggedIn User's Profile
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              required:
                - fullName
              type: object
              properties:
                fullName:
                  type: string
                  example: John Doe
                birthday:
                  type: string
                  example: 2023-03-30T17:24:12.000Z
                headline:
                  type: string
                  example: Headline About John Doe.
                location:
                  type: string
                  example: Canada, Vancouver
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/change-password:
    patch:
      tags:
        - Users
      operationId: Change Password
      description: Change The LoggedIn User's Password
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              required:
                - currentPassword
                - newPassword
              type: object
              properties:
                currentPassword:
                  type: string
                  example: $1234abcd
                newPassword:
                  type: string
                  example: $abcd1234
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


  /users/regions:
    get:
      tags:
        - Users
      operationId: Regions List
      description:  Get a List of Regions
      parameters:
        - name: keyword
          in: query
          description: Search keyword for filtering regions
          schema:
            type: string
          examples:
            example1:
              summary: Search for regions containing "Vancouver"
              value: "Vancouver"
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/RegionsData"
                  meta:
                    $ref: "#/components/schemas/RegionsMeta"

components:
  schemas:
    Login:
      type: array
      items:
        type: object
        properties:
          accessToken:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImhzYW1pZC5hYWgwQGdtYWlsLmNvbSIsIklEIjoiMGFmMTI5ODMtODMzZS00ZDQ0LWJkMzAtNDczOWUyZjBjYmYyIiwiZXhwIjoxNzA5NDY3NjM2LCJpYXQiOjE3MDk0NjA0MzYsImlzcyI6Im1vaGFtbWFkIn0.eU6UyDmdVlIWnuOVQyLi8iVci6WQFa1Tjxl7FMEcQ2U
    Profile:
      type: array
      items:
        type: object
        properties:
          fullName:
            type: string
            example: John Doe
          email:
            type: string
            example: John.Doe@gmail.com
          birthday:
            type: string
            example: 2023-03-30T17:24:12Z
          headline:
            type: string
            example: New Headline About User
          location:
            type: string
            example: Canada, Vancouver
    RegionsData:
      type: array
      items:
        type: object
        properties:
          ID:
            type: string
            example: 479661dc-3ec6-492b-83b0-e2f11337511a
          Country:
            type: string
            example: Canada
          City:
            type: string
            example: Vancouver
    RegionsMeta:
      type: array
      items:
        type: object
        properties:
          totalItems:
            type: integer
            example: 44662
          totalPages:
            type: integer
            example: 4467
          current:
            type: integer
            example: 10
          next:
            type: integer
            example: 11
          previous:
            type: integer
            example: 9
          perPage:
            type: integer
            example: 10
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
